### ISSUE TITLE
comet tails follow whichever star is closest to the camera.

### ISSUE THREAD

**Issue by GregroxMun** [R-T-B/Kopernicus#23]
from one angle it follows the big star (Kaywell)
![image](https://user-images.githubusercontent.com/9667986/90314210-0a981100-dee0-11ea-9337-0d14a94074b6.png)

from another it follows the small star (Limnell)
![image](https://user-images.githubusercontent.com/9667986/90314223-1daae100-dee0-11ea-9b99-b2332891c802.png)

Not sure what the physically correct behavior would be--ion tail pointing at some weighted center of where the illumination is coming from? Two ion tails with different brightnesses depending on the illumination source)

An easier solution might be to have the comet tail always follow only the star which the comet receives the most heat from.

**Comment by R-T-B** [comment]
"An easier solution might be to have the comet tail always follow only the star which the comet receives the most heat from."

Yep, that is the eventual plan.

**Comment by R-T-B** [comment]
I will be reimplementing comets hopefully over the next week in Kopernicus code like we do for asteroids.  While I'm at it, I'll make sure this code becomes star-aware.  Right now it obviously is not.

**Comment by GregroxMun** [comment]
for what it's worth, I asked my friend Dr. Alicia Aarnio, a stellar physicist, about how the comets _should_ behave.

**Gregrox:** can you help me answer a question about comet tails? Here we have a comet orbiting two stars. How would the tails behave? Would there be two ion tails, one for each star? Would the ion tail point away from some weighted center of where both starlight is coming from? What if the comet were between two stars?
currently, the implementation of comets in this game supports only a single star. For my modded three-star system, the comet's tail changes where it's pointing based on the position of the camera.

**Dr. Alicia Aarnio**
Hmm, I can try- that's a really good question. Orbiting a single star, the ion tail would always point radially away from the star. For a double star system, it would depend what the net stellar wind flux is on the comet from both stars. This, in turn, depends on the masses and ages of the stars in the system. If they were both main sequence, I'd wager the ion tail would point away from the more massive star. If the low-mass star is pre-main sequence, well.. M dwarfs are kind of a different beast altogether, they have higher levels overall of activity. We don't know much about stellar winds because they're extremely hard to measure, but you could guess that M dwarfs probably have more frequent coronal mass ejections, so the comet might have an ion tail that mainly points away from the higher mass star, but has sporadic shifts in direction as the M dwarf activity happens.

**Comment by R-T-B** [comment]
So in a simple sim, point away from the star with the highest flux-at-location probably?  Because we can do that.

**Comment by 7ranceaddic7** [comment]
Umm, I think in a simple system (all things being otherwise equal) a coment tail would be the result the combined radial vector.  I think the Kerbal-verse is all main sequence stars.  So, pointing mostly away from the highest-flux star but not completely perpendicular.

**Comment by R-T-B** [comment]
> 
> 
> Umm, I think in a simple system (all things being otherwise equal) a coment tail would be the result the combined radial vector. I think the Kerbal-verse is all main sequence stars. So, pointing mostly away from the highest-flux star but not completely perpendicular.

That could be done.  It's slightly more complicated math but nothing terrible.  As long as it doesn't present a horrendous code challenge in some way (it shouldn't) this is probably what I'll attempt.

**Comment by GregroxMun** [comment]
> 
> 
> Umm, I think in a simple system (all things being otherwise equal) a coment tail would be the result the combined radial vector. I think the Kerbal-verse is all main sequence stars. So, pointing mostly away from the highest-flux star but not completely perpendicular.

don't think that works. not everyone puts their binary stars in actual binary orbits (barycenters are very hard)

**Comment by GregroxMun** [comment]
> 
> 
> Umm, I think in a simple system (all things being otherwise equal) a coment tail would be the result the combined radial vector. I think the Kerbal-verse is all main sequence stars. So, pointing mostly away from the highest-flux star but not completely perpendicular.

main sequence stars can have vastly different luminosities. The relative luminosity must be accounted for.

**Comment by 7ranceaddic7** [comment]
I don't know one way or the other, what fluxes are modeled in Kopernicus?

**Comment by R-T-B** [comment]
> 
> 
> I don't know one way or the other, what fluxes are modeled in Kopernicus?

Basically, we use the ingame flux system just multiplied by more stars.  So vessels in KSP have a function I can call to get "flux at location" which is essentially the amount of energy hitting a vessel at a location.  With Kopernicus, we can do that too, we just have an additonal parameter for a star.  So we can directly ask the game how much energy at a location is coming from a given star.

After determining that, we can then determine the direction of the star relative to the craft (comets are modeled as vessels, believe it or not, in game logic).  Then, we can do whatever we want to model it based on those two paraemeters basically.

So for KSP, it's pretty simple.  Flux is just energy emitted from a star.

**Comment by R-T-B** [comment]
This is going on the backburner for a tiny bit though, my workload at work has increased, and CKAN of version 1.9.1 is our top priority.

I still consider these comet bugs important, just want to update you that this will probably not be happening this week.

**Comment by WhirligigGirl** [comment]
was this issue closed because it is not going to be supported, or because it has been fixed? I don't see anything in the changelogs about it.

**Comment by R-T-B** [comment]
I believe it was closed because this would be something that would require harmony, which at the time our official policy was "nope."  I'll reopen it now that we actually gave in and use harmony though.

It's not fixed yet, I do not think.
